version: "3.7"
services:
  db:
      image: mysql:latest
      container_name: mysql18_server
      environment:
         MYSQL_ROOT_PASSWORD: "passw0rd!"
      expose:
         - 3306
      volumes:
         - /share/mysql_django/:/docker-entrypoint-initdb.d
         - /share/mysql_django/mysql_data:/var/lib/mysql
      networks:
        customnetwork:
          ipv4_address: 172.10.0.9
  web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: pydjango_env
      volumes:
        - /share/NTNUBookWeb/:/home/pyDjango/
      ports:
        - 8000:80
      depends_on:
        - db
      networks:
        customnetwork:
          ipv4_address: 172.10.0.10
      links:
        - db:db
      working_dir: /home/pyDjango
      command: ./wait-for-it.sh db:3306 --timeout=60 --strict -- python manage.py runserver

networks:
  customnetwork:
    ipam:
      config:
        - subnet : 172.10.0.0/16